name: Build tools cache
on:
  push:
    branches:
      - master

  schedule:
    # Each day at midnight
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - ubuntu-18.04
          - ubuntu-16.04
          - macos-10.15
        crate:
          - cargo-audit
          - cargo-udeps
          - cargo-nono
          - cargo-geiger
          - cargo-tarpaulin
          - cargo-cache
          - cargo-web
          - cargo-tree

          - cross
          - sccache
          - mdbook
          - wasm-pack
          - wasm-bindgen-cli
          - grcov

        exclude:
          # cargo-tarpaulin is available for Linux only
          - crate: cargo-tarpaulin
            os: windows-2019
          - crate: cargo-tarpaulin
            os: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Build ${{ matrix.crate }}
        run: python build.py
        env:
          CRATE: ${{ matrix.crate }}
          RUNNER: ${{ matrix.os }}
          AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SIGN_CERT: ${{ secrets.SIGN_CERT }}
          SIGN_CERT_PASSPHRASE: ${{ secrets.SIGN_CERT_PASSPHRASE }}
